version: '3.7'
services:
  db:
    image: mongo
    container_name: db
    env_file: ./db/env
    volumes:
      - "./db/data:/data/db"
    networks:
      exchange:
        ipv4_address: 10.10.0.2
  web:
    container_name: web
    build: web
    ports:
      - "80:8080"
    networks:
      exchange:
        ipv4_address: 10.10.0.3

networks:
  exchange:
    ipam:
      config:
        - subnet: 10.10.0.0/24
